# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BMEG.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BMEG.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nBMEG.proto\"\xc2\x02\n\x0f\x42MEG_Clustering\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\x08metadata\x18\x02 \x01(\x0b\x32$.BMEG_Clustering.clustering_metadata\x12\x31\n\x06groups\x18\x03 \x03(\x0b\x32!.BMEG_Clustering.clustering_group\x1a\\\n\x13\x63lustering_metadata\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x30\n\nmembertype\x18\x02 \x01(\x0e\x32\x1c.BMEG_Clustering.member_type\x1a\x31\n\x10\x63lustering_group\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07members\x18\x02 \x03(\t\"%\n\x0bmember_type\x12\x0b\n\x07SAMPLES\x10\x00\x12\t\n\x05GENES\x10\x01\x62\x06proto3')
)



_BMEG_CLUSTERING_MEMBER_TYPE = _descriptor.EnumDescriptor(
  name='member_type',
  full_name='BMEG_Clustering.member_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SAMPLES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENES', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=300,
  serialized_end=337,
)
_sym_db.RegisterEnumDescriptor(_BMEG_CLUSTERING_MEMBER_TYPE)


_BMEG_CLUSTERING_CLUSTERING_METADATA = _descriptor.Descriptor(
  name='clustering_metadata',
  full_name='BMEG_Clustering.clustering_metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='BMEG_Clustering.clustering_metadata.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='membertype', full_name='BMEG_Clustering.clustering_metadata.membertype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=247,
)

_BMEG_CLUSTERING_CLUSTERING_GROUP = _descriptor.Descriptor(
  name='clustering_group',
  full_name='BMEG_Clustering.clustering_group',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BMEG_Clustering.clustering_group.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='members', full_name='BMEG_Clustering.clustering_group.members', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=298,
)

_BMEG_CLUSTERING = _descriptor.Descriptor(
  name='BMEG_Clustering',
  full_name='BMEG_Clustering',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BMEG_Clustering.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='BMEG_Clustering.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='groups', full_name='BMEG_Clustering.groups', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BMEG_CLUSTERING_CLUSTERING_METADATA, _BMEG_CLUSTERING_CLUSTERING_GROUP, ],
  enum_types=[
    _BMEG_CLUSTERING_MEMBER_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=337,
)

_BMEG_CLUSTERING_CLUSTERING_METADATA.fields_by_name['membertype'].enum_type = _BMEG_CLUSTERING_MEMBER_TYPE
_BMEG_CLUSTERING_CLUSTERING_METADATA.containing_type = _BMEG_CLUSTERING
_BMEG_CLUSTERING_CLUSTERING_GROUP.containing_type = _BMEG_CLUSTERING
_BMEG_CLUSTERING.fields_by_name['metadata'].message_type = _BMEG_CLUSTERING_CLUSTERING_METADATA
_BMEG_CLUSTERING.fields_by_name['groups'].message_type = _BMEG_CLUSTERING_CLUSTERING_GROUP
_BMEG_CLUSTERING_MEMBER_TYPE.containing_type = _BMEG_CLUSTERING
DESCRIPTOR.message_types_by_name['BMEG_Clustering'] = _BMEG_CLUSTERING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BMEG_Clustering = _reflection.GeneratedProtocolMessageType('BMEG_Clustering', (_message.Message,), dict(

  clustering_metadata = _reflection.GeneratedProtocolMessageType('clustering_metadata', (_message.Message,), dict(
    DESCRIPTOR = _BMEG_CLUSTERING_CLUSTERING_METADATA,
    __module__ = 'BMEG_pb2'
    # @@protoc_insertion_point(class_scope:BMEG_Clustering.clustering_metadata)
    ))
  ,

  clustering_group = _reflection.GeneratedProtocolMessageType('clustering_group', (_message.Message,), dict(
    DESCRIPTOR = _BMEG_CLUSTERING_CLUSTERING_GROUP,
    __module__ = 'BMEG_pb2'
    # @@protoc_insertion_point(class_scope:BMEG_Clustering.clustering_group)
    ))
  ,
  DESCRIPTOR = _BMEG_CLUSTERING,
  __module__ = 'BMEG_pb2'
  # @@protoc_insertion_point(class_scope:BMEG_Clustering)
  ))
_sym_db.RegisterMessage(BMEG_Clustering)
_sym_db.RegisterMessage(BMEG_Clustering.clustering_metadata)
_sym_db.RegisterMessage(BMEG_Clustering.clustering_group)


# @@protoc_insertion_point(module_scope)
