# Dockerfile_cluster_data_to_protograph
# convert cluster data into BMEG protograph

FROM python:3
FROM openjdk:8

## Remain current
RUN apt-get update -qq
RUN apt-get dist-upgrade -y

RUN apt-get install -y python3-pip

## install python packages
RUN pip3 install protobuf

## install protograph jar
WORKDIR /bmeg_lib
RUN wget -q --output-document=/bmeg_lib/protograph.jar https://github.com/bmeg/protograph/releases/download/0.0.15/protograph-0.0.15-standalone.jar

## copy schema files
COPY lib/BMEG_pb2.py /bmeg_lib
COPY lib/cluster.yml /bmeg_lib

## copy BMEG_addData.py tool
COPY lib/BMEG_addData.py /bmeg_lib

## copy makefile
#COPY lib/docker_tasks.mak /bmeg_lib/Makefile

## copy clusters_to_protograph.sh
COPY lib/clusters_to_protograph.sh /bmeg_lib/.
RUN chmod ugo+x /bmeg_lib/clusters_to_protograph.sh

## copy help stuff
COPY lib/help.sh /bmeg_lib/.
RUN chmod ugo+x /bmeg_lib/help.sh
COPY lib/help.txt /bmeg_lib/.

## copy example directory
COPY example /example

## default command
CMD ./help.sh

## to run scripts, do this in your data directory
## docker run -ti --entrypoint ./clusters_to_protograph.sh -v `pwd`:/data stuartlab/convert_cluster_data_to_protograph
